### PR TITLE
`aorsf` 0.1.2

### LINKED ISSUE #338: update for `aorsf` version 0.1.2
Hello!

I am planning to release `aorsf` version 0.1.2 soon. This release will include support for classification and regression oblique random forests, and these new features introduce some new parameters into `orsf`, deprecate the current `orsf_control` functions in favor of outcome-specific ones, and replace the `orsf_fit` class with `ObliqueForest`. Last, the ArXiv paper that we reference in the mlr3 docs has now been published in Journal of Computational and Graphical Statistics, so the bib data can be updated. I've prepared a PR with these changes. Would it be okay for me to submit this PR for you to review?

### PR DESCRIPTION
**Pull request by bcjaeger**
Resolves #338 

- Updates the use of `orsf_control` functions, using the newer versions that are introduced in 0.1.2
- Updates the class of `orsf` models
- Updates defaults in the learner code
- Updates publication info

### CODE REVIEW

File: R/learner_aorsf_surv_aorsf.R [hunk 1]
```diff
@@ -117,31 +119,36 @@ LearnerSurvAorsf = R6Class("LearnerSurvAorsf",
...
+          aorsf::orsf_control_survival(
+            method = "net",
+            net_mix = dflt_if_null(pv, "control_net_alpha"),
+            target_df = dflt_if_null(pv, "control_net_df_target")
           )
         }
       )
       # these parameters are used to organize the control arguments
       # above but are not used directly by aorsf::orsf(), so:
       pv$control_type = NULL
```
Comment (sebffischer) [inline R/learner_aorsf_surv_aorsf.R:148]: You could used `mlr3misc::remove_named()` here

**Review by sebffischer — APPROVED** [review]
Thanks, looking good good. Only one suggestion but this is just style and up to you whether you want to do this :)

File: R/learner_aorsf_surv_aorsf.R [hunk 2]
```diff
@@ -117,35 +119,40 @@ LearnerSurvAorsf = R6Class("LearnerSurvAorsf",
...
       # above but are not used directly by aorsf::orsf(), so:
-      pv$control_type = NULL
-      pv$control_fast_do_scale = NULL
-      pv$control_fast_method = NULL
-      pv$control_cph_method = NULL
-      pv$control_cph_eps = NULL
-      pv$control_cph_iter_max = NULL
-      pv$control_net_alpha = NULL
-      pv$control_net_df_target = NULL
+      mlr3misc::remove_named(pv, c("control_type",
```
Comment (sebffischer) [inline R/learner_aorsf_surv_aorsf.R:148]:
```suggestion
      pv = remove_named(pv, c("control_type",
```

**Review by sebffischer — CHANGES_REQUESTED** [review]
